services:
  bot:
    container_name: bot
    image: localhost:5000/bot_image
    restart: always
    volumes:
      - pg_logs:/var/log/
    env_file: 
      - .env
    networks:
      - network
    depends_on:
      - db

  db:
    container_name: db
    image: localhost:5000/db_image
    restart: always
    volumes:
      - pg_logs:/var/log/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file: 
      - .env
    networks:
      - network

  db_repl:
    container_name: db_repl
    image: localhost:5000/db_repl_image
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file: 
      - .env
    networks:
      - network
    depends_on:
      - db

volumes:
  pg_data:
  pg_logs:

networks:
  network:
    driver: bridge
